//! `parse_tests.rs` is generated by build.rs

#[test]
fn unescaped_angle_test() {
    let info = xml_files::get_test_info("unescaped-angle");
    let f = info.open_xml_file();
}

#[test]
fn pi_stray_text_test() {
    let info = xml_files::get_test_info("pi-stray-text");
    let f = info.open_xml_file();
}
