[package]
name = "webern-ezxml"
version = "0.1.0"
authors = ["Matthew James Briggs <matthew.james.briggs@gmail.com>"]
edition = "2018"

[dependencies]
snafu = "0.6.2"
env_logger = "0.7.1"
log = "0.4.8"
