name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - run: cargo clippy -- --version && cargo fmt -- --version
      - run: cargo fmt -- --check
      - run: cargo clippy --locked -- -D warnings
      - run: cargo clippy --tests --locked -- -D warnings
      - run: cargo build --locked -p drop-dir
      - name: drop-dir
        run: cd drop-dir && cargo test --all-features --locked
      - name: ezxml
        run: |
          cd ezxml && cargo build && \
          cargo test && \
          cargo test --all-features && \
          cargo clippy --tests --locked -- -D warnings && \
          cargo clippy --locked -- -D warnings