name: Rust

on:
  push:
    # drop-dir is temporary, remove later
    branches: [ master, drop-dir ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust Toolchain
      run: rustup update stable
    - name: Check Code Formatting
      run: cargo fmt -- --check
    - name: Run Linter
      run: cargo clippy --locked -- -D warnings
    - name: Build drop-dir
      run: cargo build --locked -p drop-dir
    - name: Test drop-dir
      run: cd drop-dir && cargo test --all-features --locked
